import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Menu from '@/app/components/header/Menu'
import Footer from '@/app/components/footer/Footer'


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Mega de Hoje - Resultado da Loteria Nacional",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="w-full  m-auto ">
          <div className="m-auto">
          <Menu />
       
          </div>
      
        <div className="px-5 h-dvh">
          {children}
        </div>
        <Footer />
        </div>
      </body>
    </html>
  );
}
